server {
  listen 80 default_server;
  listen [::]:80 default_server;

  server_name _;
  root /var/www/kiosk-home-display;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(?:css|js|mjs|png|jpg|jpeg|gif|svg|ico|mp3|woff2?)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
